### ISSUE TITLE
Unable to override software

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#105]
Just got this deterministic error during installation on ubuntu x64 VM:

```
Performing File System Copy fscopy.java.7
Copying /usr/lib/jvm/java-8-openjdk-amd64 to /home/malte/eclipse/test-neon/software/java
Created destination /home/malte/eclipse/test-neon/software/java
Caught FileAlreadyExistsException for /home/malte/eclipse/test-neon/software/java Continue.
com.github.maybeec.oomph.task.fscopy.core.exceptions.FSCopyException: java.nio.file.NoSuchFileException:/usr/lib/jvm/java-8-openjdk-amd64/src.zip
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.copy(FSCopyUtilImpl.java:57)
  at com.github.maybeec.oomph.task.fscopy.impl.FileSystemCopyTaskImpl.perform(FileSystemCopyTaskImpl.java:316)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3151)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3079)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3060)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2960)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.nio.file.NoSuchFileException: /usr/lib/jvm/java-8-openjdk-amd64/src.zip
  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
  at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
  at java.nio.file.Files.copy(Files.java:1274)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl$1.copy(FSCopyUtilImpl.java:138)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl$1.visitFile(FSCopyUtilImpl.java:125)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl$1.visitFile(FSCopyUtilImpl.java:1)
  at java.nio.file.Files.walkFileTree(Files.java:2670)
  at java.nio.file.Files.walkFileTree(Files.java:2742)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.fileWalkCopy(FSCopyUtilImpl.java:120)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.copy(FSCopyUtilImpl.java:53)
  at com.github.maybeec.oomph.task.fscopy.impl.FileSystemCopyTaskImpl.perform(FileSystemCopyTaskImpl.java:316)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3151)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3079)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3060)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2960)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:556)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:682)
  ... 1 more
```

might be caused by themetalone/oomph-fork#7.
However, it should never occur, just override the sources. This might also be an update of the current JDK installed and may be the same for any other external software dependency.

**Comment by themetalone** [comment]
I think the problem here is the +src.zip+. This isn't an actual zip file but a symbolic link pointing to something. Ubuntu itself (lubuntu 14 x32) seems to have problems with this file. 

Maybe I should exclude symbolic links (if possible) from the copy process

**Comment by themetalone** [comment]
non-existent files are now ignored during the copy process. This includes symbolic links into nowhere. The error didn't occur on my vm anymore
