### ISSUE TITLE
Checkstyle update site not available?

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j-ide#115]
```
ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://sourceforge.net/projects/eclipse-cs/files/updatesite/6.16.0.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:333)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:236)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:456)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1613)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:428)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by themetalone** [comment]
Cannot reproduce it, neither on my linux machine this morning nor on my windows machine now. Maybe just a little hickup of their server?

**Comment by maybeec** [comment]
I again had this issue some times while testing. Maybe we should better go with the official update site http://eclipse-cs.sf.net/update ?

**Comment by maybeec** [comment]
It seems, that we have two update sites declared in the product:

http://sourceforge.net/projects/eclipse-cs/files/updatesite/6.16.0
and
http://eclipse-cs.sf.net/update/

we should remove the first one. As this is stated to be the errorneous update site in the logs.
