### ISSUE TITLE
Unexpected error accessing secure storage, falling back to in memory store for credentials.

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j-ide#45]
Yet another design flaw of eclipse. The credential store is actually bound to the eclipse installation that seems to ship the credentials for encryption of the store so it can not be shared across eclipse installations what was actually the goal.
However the eclipse default of having the store inside the eclipse software directory is still the worst option as this causes that people ZIP up a software package and accidentally share and spread all their passwords. That is really totally odd.
So we would need to have a unique identifier for each oasp4j-ide installation that we can append to the store path to make it work.

> org.eclipse.equinox.security.storage.StorageException: Unable to locate secure storage module (org.eclipse.equinox.security.windowspasswordprovider).
	at org.eclipse.equinox.internal.security.storage.PasswordProviderSelector.findStorageModule(PasswordProviderSelector.java:190)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getModulePassword(SecurePreferencesRoot.java:231)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesRoot.getPassword(SecurePreferencesRoot.java:224)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.get(SecurePreferences.java:262)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.get(SecurePreferencesWrapper.java:106)
	at org.eclipse.mylyn.internal.commons.repositories.core.SecureCredentialsStore.get(SecureCredentialsStore.java:86)
	at org.eclipse.mylyn.tasks.core.TaskRepository.getAuthInfo(TaskRepository.java:306)
	at org.eclipse.mylyn.tasks.core.TaskRepository.getCredentials(TaskRepository.java:381)
	at org.eclipse.mylyn.internal.tasks.core.TaskRepositoryLocation.getCredentials(TaskRepositoryLocation.java:59)
	at org.eclipse.mylyn.commons.net.WebUtil.createHostConfiguration(WebUtil.java:283)
	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaClient.authenticate(BugzillaClient.java:495)
	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaClient.getSearchHits(BugzillaClient.java:672)
	at org.eclipse.mylyn.internal.bugzilla.core.BugzillaRepositoryConnector.performQuery(BugzillaRepositoryConnector.java:394)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:312)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:269)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:201)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeRepositoriesJob.updateQueries(SynchronizeRepositoriesJob.java:187)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeRepositoriesJob.run(SynchronizeRepositoriesJob.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by hohwille** [comment]
Maybe the easiest solution is to move the store to the conf directory of the oasp4j-ide installation (conf/eclipse/.keyring).

**Comment by hohwille** [comment]
Seems to be a general bug in Eclipse Luna SR2. Then no change in oasp4j-ide is required and SR2 has to be avoided or patched/updated.

**Comment by lgoerlach** [comment]
Error doesn't occur anymore in release candidate 1.4.0
